// Compilation unit for libmathc.a
#include "combinatorics.h"
#include "ml_complex.h"
#include "exponential.h"
#include "fft.h"
#include "integral.h"
#include "numerical.h"
#include "ode.h"
#include "optimization.h"
#include "polynomial.h"
#include "quadratics.h"
#include "statistics.h"
#include "trigonometry.h"
#include "simd.h"
#include "ieee754.h"
#include "profiles.h"
#include "simd_batch.h"
#include "quaternion.h"
